# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48d4acbdc75925e37c5320d6e78bf1c8378b566676099888e4fa6d94cbf0e5a5db44f6c3f2d0ced3bd72d58cfbf905b05530574c861f63924072f05a97a01c36

test:
  secret_key_base: 4ec5f95bf2b0577fc53d8d3ef3a6f75c9d5e770b5955c625df4125f586750207247ac6f90789586a2a0e295b6b7e811b18e72318490c1c2794a6738cdf620bee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
